# Generated by Django 3.2.5 on 2021-08-01 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('menu_title', models.CharField(blank=True, default='', max_length=255)),
                ('short', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('html', 'HTML'), ('items_tree', 'Items tree'), ('items_list', 'Items list'), ('include_item', 'Inclue item'), ('.property', 'Property'), ('.conf', 'Node conf'), ('inclusion_point', 'Inclusion point'), ('render_view', 'Render view')], default='html', max_length=32, verbose_name='Type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, default='')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('link', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MessyCMS.node')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MessyCMS.node')),
                ('sites', models.ManyToManyField(blank=True, null=True, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
