# Generated by Django 3.2.5 on 2021-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessCMS', '0003_auto_20210710_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='menu_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='short',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
