# Generated by Django 3.2.5 on 2021-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessCMS', '0005_auto_20210711_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fmt',
            field=models.CharField(choices=[('html', 'HTML')], default='html', max_length=32, verbose_name='Type'),
        ),
    ]
